name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup GitHub Pages dependencies
      - name: Setup Pages
        uses: actions/setup-pages@v2

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ./public
          cp index.html ./public/
          echo "Deployment to GitHub Pages successful!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
